dist: bionic
sudo: false
addons:
   apt:
      update: true
      
language: python
python: 
  - "3.6"
  - "3.7"
  - "3.8"

install:
   - pip install -r requirements.txt
   - pip -V
   - python setup.py install
   - pip install nose
   - source install.sh 

script:
  nosetests -v --cover-packge=l2l/tests
